name: mediasoup-rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
          - windows-2019
        rust:
          - stable
          # - nightly

    runs-on: ${{ matrix.os }}

    steps:
      - name: Add MSVC compiler
        uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'

      # This is needed as a workaround for GNU linker being first in PATH and thus preventing Meson from finding MSVC
      # linker.
      - name: Remove GNU linker for MSVC
        shell: bash
        run: rm /usr/bin/link
        if: runner.os == 'Windows'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Configure cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.toml') }}

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: cargo test
        uses: actions-rs/cargo@v1
        env:
          KEEP_BUILD_ARTIFACTS: '1'
        with:
          command: test
          args: --verbose
