[package]
name = "mediasoup"
version = "0.9.1"
description = "Cutting Edge WebRTC Video Conferencing in Rust"
categories = ["api-bindings", "multimedia", "network-programming"]
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2018"
license = "ISC"
keywords = ["webrtc", "ortc", "sfu"]
documentation = "https://docs.rs/mediasoup"
repository = "https://github.com/versatica/mediasoup"
readme = "README.md"
include = [
    "/benches",
    "/src",
    "/README.md"
]

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
targets = []

[dependencies]
async-channel = "1.6.1"
async-executor = "1.4.1"
async-lock = "2.4.0"
async-oneshot = "0.5.0"
async-trait = "0.1.51"
atomic-take = "1.0.0"
event-listener-primitives = "2.0.1"
fastrand = "1.5.0"
futures-lite = "1.12.0"
h264-profile-level-id = "0.1.1"
hash_hasher = "2.0.3"
log = "0.4.14"
nohash-hasher = "0.2.0"
once_cell = "1.8.0"
serde_json = "1.0.67"
serde_repr = "0.1.7"
thiserror = "1.0.28"

[dependencies.lru]
default-features = false
version = "0.6.6"

[dependencies.mediasoup-sys]
path = "../worker"
version = "0.3.1"

[dependencies.parking_lot]
version = "0.11.2"
features = ["serde"]

[dependencies.regex]
default-features = false
features = ["std", "perf"]
version = "1.5.4"

[dependencies.serde]
features = ["derive"]
version = "1.0.130"

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.8.2"

[dev-dependencies]
actix = "0.12.0"
actix-web-actors = "4.0.0-beta.6"
async-io = "1.6.0"
criterion = "0.3.5"
env_logger = "0.9.0"

[dev-dependencies.actix-web]
default-features = false
version = "4.0.0-beta.8"

[[bench]]
name = "direct_data"
harness = false
